IRO_Webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('shelters/', include('shelters_page.urls')),
    path('donate/', include('donate_page.urls')),
    path('iro-faqs/', include('faqs_page.urls')),
    path('adoption/', include('adoption.urls')),
    path('adoption-process/', include('adoption_process.urls')),
    path('management/', include('management.urls')),
    path('educational-resources/', include('educ_reso.urls')),
    path('news&articles/', include('news_artic.urls')),
    path('volunteer/', include('volunteer.urls')),
    path('content-page/', include('content_page.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("about_us/", include('about_us.urls')),
    path("contact_us/", include('contact_us.urls')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"), 
] 

management/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'management'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.admin_login, name='login'),
    path('logout/', views.admin_logout, name='logout'),
    # path('edit-account/', auth_views.PasswordChangeView.as_view(template_name='accounts/edit.html'), name='edit_account'),
    path('edit-account/', views.PasswordsChangeView.as_view(), name='edit_account'),
    path('edit-account-success/', views.edit_account_success, name='edit-account-success'),

    
    path('dashboard/', views.dashboard, name='dashboard'),
    
    path('homepage/hero-section', views.homepage_hero_section, name='homepage_hero_section'),
    path('homepage/stats', views.homepage_stats, name='homepage_stats'),
    path('homepage/add-stats', views.add_homepage_stats, name='add_homepage_stats'),
    path('homepage/edit-stats/<int:id>', views.edit_homepage_stats, name='edit_homepage_stats'),
    path('homepage/delete-stat', views.delete_homepage_stats, name='delete_homepage_stats'),

    path('wishlists', views.wishlists, name='wishlists'),
    path('add-wishlist', views.add_wishlist, name='add_wishlist'),
    path('edit-wishlist/<int:id>', views.edit_wishlist, name='edit_wishlist'),
    path('delete-wishlist', views.delete_wishlist, name='delete_wishlist'),


    path('educational-resources', views.educational_resources, name='educational_resources'),
    path('add-resource', views.add_resource, name='add_resource'),
    path('edit-resource/<int:id>/', views.edit_resource, name='edit_resource'),
    path('delete-resource', views.delete_resource, name='delete_resource'),
    
    path('category-education-resources', views.category_resources, name='category_resources'),
    path('add-category-education-resources', views.add_category_resources, name='add_category_resources'),
    path('edit-category-education-resources/<int:id>/', views.edit_category_resources, name='edit_category_resources'),
    path('delete-category-education-resources', views.delete_category_resources, name='delete_category_resources'),
    
    path('news-articles', views.news_and_articles, name='news_articles'),
    path('add-news&articles', views.add_news_and_articles, name='add_news&articles'),
    path('edit-news&articles/<int:id>/', views.edit_news_and_articles, name='edit_news&articles'),
    path('delete-news&articles', views.delete_news_and_articles, name='delete_news&articles'),
    
    path('category-news&articles', views.category_news_and_articles, name='category_news&articles'),
    path('add-category-news&articles', views.add_category_news_and_articles, name='add_category_news_and_articles'),
    path('edit-category-news&articles/<int:id>/', views.edit_category_news_and_articles, name='edit_category_news_and_articles'),
    path('delete-category-news&articles', views.delete_category_news_and_articles, name='delete_category_news_and_articles'),
    
    path('adoptable-rescues/', views.adoptable_rescues, name='adoptable_rescues'),
    path('add_rescue/', views.add_rescue, name='add_rescue'),
    path('adoptable-rescue/<int:rescue_id>/edit/', views.edit_rescue, name='edit_rescue'),
    path('adoptable-rescue/delete/', views.delete_rescue, name='delete_rescue'),
    path('adoptable-rescue/<int:pk>/', views.view_rescue, name='view_rescue'),
    
    path('google-forms/', views.google_form_list, name='google_form_list'),
    path('google-forms/new/', views.google_form_create, name='google_form_create'),
    path('google-forms/<int:pk>/edit/', views.google_form_update, name='google_form_update'),
    path('google-forms/<int:pk>/delete/', views.google_form_delete, name='google_form_delete'),
    
    path('faqs', views.faqs, name='faqs'),
    path('add-faqs', views.add_faqs, name='add_faqs'),
    path('edit-faqs/<int:id>', views.edit_faqs, name='edit_faqs'),
    path('delete-faqs', views.delete_faqs, name='delete_faqs'),

] 

management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
from django.contrib import messages
from django.http import JsonResponse
from django.conf import settings
from django.db.utils import IntegrityError
from django.db.models import Q
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm


# Create your views here.
def admin_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        
        if user:
            login(request, user)
            return redirect(reverse('management:dashboard'))
        else:
            messages.error(request, "Wrong username or password.")
            
    if request.user.is_authenticated:
        return redirect(reverse('management:dashboard'))
    return render(request, 'accounts/login.html')

def admin_logout(request):
    logout(request)
    return redirect(reverse('management:login'))


class PasswordsChangeView(PasswordChangeView):
    form_class = EditUserForm
    template_name='accounts/edit.html'
    # form_class = PasswordChangeForm
    success_url = reverse_lazy('management:edit-account-success')

def edit_account_success(request):
    return render(request, 'accounts/edit_success.html')
    

@login_required()
def dashboard(request):
    return render(request, 'dashboard/dashboard.html')


# Home page functions
@login_required()
def homepage_hero_section(request):
    homepage = HomePage.objects.first()
    if request.method == 'POST':
        form = HomePageForm(request.POST, request.FILES, instance=homepage)
        if form.is_valid():
            form.save()
            return redirect('management:homepage_hero_section')  # Redirect to avoid resubmission
    else:
        form = HomePageForm(instance=homepage)
    return render(request, 'homepage/hero_section.html', {'form': form})

@login_required()
def homepage_stats(request):
    
    stats = HomePageStats.objects.all().order_by('-created_at')
    
    search_query = request.GET.get('search', '').strip()
    if search_query:
        stats = stats.filter(
            Q(name__icontains=search_query)|
            Q(number__icontains=search_query)
        )
        
    datesorted = request.GET.get('date-sort', '').strip()
    if datesorted == 'ascending':
        stats = stats.order_by('created_at')
    
    return render(request, 'homepage/stats_section/stats_section.html', {
        'stats': stats,
        'search_query': search_query,
        'datesorted': datesorted,
    })
    
@login_required()
def add_homepage_stats(request):
    if request.method == 'POST':
        form = HomePageStatsForm(request.POST, request.FILES)  # Include request.FILES for file uploads
        if form.is_valid():
            stat = form.save()
            messages.success(request, 'Stat added successfully!')
            return redirect(reverse('management:homepage_stats'))

    form = HomePageStatsForm()

    return render(request, 'homepage/stats_section/add_stats.html', {
        'form': form,
    })    
    
@login_required()
def edit_homepage_stats(request, id):
    if request.method == 'POST':
        stat = get_object_or_404(HomePageStats, id=id)
        form = HomePageStatsForm(request.POST, request.FILES, instance=stat)  # Include request.FILES for file uploads
        if form.is_valid():
            stat = form.save()
            messages.success(request, 'Stat edited successfully!')
            return redirect(reverse('management:homepage_stats'))

    stat = get_object_or_404(HomePageStats, id=id)
    form = HomePageStatsForm(instance=stat)

    return render(request, 'homepage/stats_section/edit_stats.html', {
        'form': form,
        'stat': stat,
    })    
    
@login_required()
def delete_homepage_stats(request):
    if request.method == "POST":
        selected_ids = request.POST.getlist('selected_ids')
        for i in selected_ids:
            selected_ids= i.split(',')
            
        HomePageStats.objects.filter(id__in=selected_ids).delete()
        
        if  len(selected_ids) > 1:
            messages.success(request, 'Stats deleted successfully')
        else:
            messages.success(request, 'Stat deleted successfully')
        return redirect(reverse('management:homepage_stats'))

    
# FAQs Functions
@login_required()
def wishlists(request):
    
    wishlists = Wishlist.objects.all().order_by('-created_at')
    
    search_query = request.GET.get('search', '').strip()
    if search_query:
        wishlists =wishlists.filter(
            Q(name__icontains=search_query)|
            Q(description__icontains=search_query)
        )
    
    datesorted = request.GET.get('date-sort', '').strip()
    if datesorted == 'ascending':
        wishlists = wishlists.order_by('created_at')
        
    return render (request, 'in_kind_donation/wishlists.html', {
        'wishlists': wishlists,
        'search_query': search_query,
        'datesorted': datesorted
    })

@login_required()
def add_wishlist(request):
    
    if request.method == "POST":
        form = WishlistForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category added successfully.')
            return redirect(reverse('management:wishlists'))
        else:
            # If the form is invalid, display the error message from `form.errors`
            if 'name' in form.errors:
                messages.error(request, 'Wishlist already exists.')
            else:
                messages.error(request, 'Error adding wishlit.')
                
    form = WishlistForm()
    return render (request, 'in_kind_donation/add_wishlist.html', {
        'form': form
    })
    
@login_required()
def edit_wishlist(request, id):
    
    if request.method == "POST":
        wishlist = get_object_or_404(Wishlist, id=id)
        form = WishlistForm(request.POST, request.FILES, instance=wishlist)
        if form.is_valid():
            form.save()
            messages.success(request, 'Wishlist edited successfully.')
            return redirect(reverse('management:wishlists'))
        else:
            # If the form is invalid, display the error message from `form.errors`
            if 'name' in form.errors:
                messages.error(request, 'Wishlist already exists.')
            else:
                messages.error(request, 'Error adding wishlit.')
                
    wishlist = Wishlist.objects.get(id=id)
    form = WishlistForm(instance=wishlist)
    return render (request, 'in_kind_donation/edit_wishlist.html', {
        'form': form,
        'wishlist': wishlist,
    })
    
    
@login_required()
def delete_wishlist(request):
    if request.method == "POST":
        selected_ids = request.POST.getlist('selected_ids')
        print(selected_ids)
        for i in selected_ids:
            selected_ids= i.split(',')
            
        Wishlist.objects.filter(id__in=selected_ids).delete()
        
        if  len(selected_ids) > 1:
            messages.success(request, 'Wishlists deleted successfully')
        else:
            messages.success(request, 'Wishlist deleted successfully')
        return redirect(reverse('management:wishlists'))

    
# Educational Resources functions
@login_required()
def educational_resources(request):
    
    resources = EducationalResource.objects.all().order_by('-created_at')
    categories = ResourceCategory.objects.all().order_by('name')
    
    search_query = request.GET.get('search', '').strip()
    if search_query:
        resources = resources.filter(
            Q(id__icontains=search_query)|
            Q(title__icontains=search_query) |
            Q(content__icontains=search_query)
        )
        
    datesorted = request.GET.get('date-sort', '').strip()
    if datesorted == 'ascending':
        resources = resources.order_by('created_at')
    
    category_filter = request.GET.get('category', '').strip()
    print(category_filter)
    if category_filter:
        category = categories.get(name=category_filter)
        resources = EducationalResource.objects.filter(
            category=category
        )
        
    return render(request, 'educational_resources/resources.html', {
        'resources': resources,
        'search_query': search_query,
        'categories': categories,
        'datesorted': datesorted,
        'category_filter': category_filter,
    })
    
    
@login_required()
def add_resource(request):
    if request.method == 'POST':
        form = EducationalResourceForm(request.POST, request.FILES)  # Include request.FILES for file uploads
        if form.is_valid():
            news_article = form.save()
            messages.success(request, 'Post added successfully!')
            return redirect(reverse('management:educational_resources'))

    form = EducationalResourceForm()

    return render(request, 'educational_resources/add_resource.html', {
        'form': form,
    })    
    
@login_required()
def edit_resource(request, id):
    if request.method == 'POST':
        resource = get_object_or_404(EducationalResource, id=id)
        form = EducationalResourceForm(request.POST, request.FILES, instance=resource)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post edited successfully.')
            return redirect(reverse('management:educational_resources'))

    resource = EducationalResource.objects.get(id=id)
    form = EducationalResourceForm(instance=resource)

    return render(request, 'educational_resources/edit_resource.html', {
        'form': form,
        'resource': resource
    })

management/templates/news&articles/add_news&articles.html
{% extends "base/base.html" %}

{% block content %}
    <div class="container mt-5 text-start ">
        <div class="card shadow-lg p-4" style="border-radius: 15px; max-width: 1000px; margin: auto;">
            <h2 class="text-center mb-4" style="font-weight: bold; color: #343a40;">Add News&Articles Post</h2>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- Title Field -->
                <div class="mb-4">
                    {{form.title.label}}
                    {{form.title}}
                </div>

                <!-- Category Field -->
                <div class="mb-4">
                    {{form.category.label}}
                    {{form.category}}
                </div>

                <!-- Featured Field -->
                <div class="mb-4">
                    {{form.featured.label}}
                    {{form.featured}}
                </div>

                <!-- Content Field -->
                <div class="mb-4">
                    {{form.media}}
                    {{form.content.label}}
                    {{form.content}}
                </div>

                <!-- Picture Upload -->
                <div class="mb-4">
                    {{form.photo.label}}
                    {{form.photo}}
                </div>

                <!-- Action Buttons -->
                <div class="d-flex justify-content-end gap-2">
                    <button 
                        type="submit" 
                        class="btn btn-primary px-4 py-2" 
                        style="border-radius: 25px; font-weight: bold;">Save Changes</button>
                    
                    <a 
                        href="{% url 'management:news_articles' %}" 
                        class="btn btn-secondary px-4 py-2" 
                        style="border-radius: 25px;">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

management/templates/news&articles/edit_news&articles.html
{% extends "base/base.html" %}

{% block content %}
    <div class="container mt-5 text-start ">
        <div class="card shadow-lg p-4" style="border-radius: 15px; max-width: 1000px; margin: auto;">
            <h2 class="text-center mb-4" style="font-weight: bold; color: #343a40;">Edit News&Articles Post</h2>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- Title Field -->
                <div class="mb-4">
                    {{form.title.label}}
                    {{form.title}}
                </div>

                <!-- Category Field -->
                <div class="mb-4">
                    {{form.category.label}}
                    {{form.category}}
                </div>

                <!-- Featured Field -->
                <div class="mb-4">
                    {{form.featured.label}}
                    {{form.featured}}
                </div>

                <!-- Content Field -->
                <div class="mb-4">
                    {{form.media}}
                    {{form.content.label}}
                    {{form.content}}
                </div>

                <!-- Picture Upload -->
                <div class="mb-4">
                    {% if news_article.photo %}
                    <div class="mt-2 text-center">
                        <img src="{{ news_article.photo.url }}" alt="Additional Picture 4"
                             class="img-fluid rounded shadow-sm"
                            >
                        <p class="text-muted mt-2">Current Picture</p>
                    </div>
                    {% else %}
                    {% endif %}
                    {{form.photo.label}}
                    {{form.photo}}
                </div>

                <!-- Action Buttons -->
                <div class="d-flex justify-content-end gap-2">
                    <button 
                        type="submit" 
                        class="btn btn-primary px-4 py-2" 
                        style="border-radius: 25px; font-weight: bold;">Save Changes</button>
                    
                    <a 
                        href="{% url 'management:news_articles' %}" 
                        class="btn btn-secondary px-4 py-2" 
                        style="border-radius: 25px;">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

management/templates/news&articles/news&articles.html
{% extends "base/base.html" %}
{% load static %}

{% block stylesheet %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
<style>
    .table {
        border-collapse: separate;
        border-spacing: 0;
        border-radius: 12px;
        overflow: hidden;
    }

    .thead-dark th {
        background-color: #231F20;
        color: #fff;
        border: none;
        text-align: center;
    }

    .table-bordered th, .table-bordered td {
        border: 1px solid #dee2e6;
    }

    .table-hover tbody tr:hover {
        background-color: rgba(0, 0, 0, 0.05);
    }

    .btn-lg {
        padding: 0.6rem 1.5rem;
    }

    .btn-outline-danger:hover {
        background-color: #dc3545;
        color: #fff;
    }

    .btn-outline-warning:hover {
        background-color: #ffc107;
        color: #fff;
    }

    .btn-outline-success:hover {
        background-color: #28a745;
        color: #fff;
    }
</style>
{% endblock stylesheet %}

{% block content %}

<div class="container text-start mt-5">
    <h1 class="mb-5 text-center display-4" style="font-weight: bold; color: #343a40;">News&Articles</h1>
     
        <div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3">

            <div class="d-flex">
                {% comment %} <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addBlogModal">Add Post</button> {% endcomment %}
                <a class="btn btn-primary me-2" href="{% url 'management:add_news&articles' %}">Add Post</a>
                <button class="btn btn-danger rounded-3" id="bulkDeleteButton" disabled>Delete Selected</button>
            </div>
            
            <!-- Search and Filter -->
            <div class="d-flex ms-auto gap-2">  
                <div>
                    <label for="date-sort">Order by date: </label>
                    <select 
                            name="date-sort" 
                            id="date-sort"
                            class="form-select shadow-sm w-auto"  
                            style="border-radius: 12px;">
                            <option value="" disabled selected>-----</option>
                            <option value="ascending" {% if datesorted == "ascending" %}selected{% endif %}>
                                Ascending   
                            </option>
                            <option value="descending" {% if datesorted  == "descending" %}selected{% endif %}>
                                Descending
                            </option>
                    </select>
                </div>
               
                <div>
                    <label for="date-sort">Category: </label>
                    <select 
                            name="category-news_article" 
                            id="category-news_article" 
                            class="form-select shadow-sm w-auto"  
                            style="border-radius: 12px;">
                            <option value="">All Categories</option>
                            {% for category in categories %}
                                <option value="{{ category.name }}" {% if category.name == category_filter %}selected{% endif %}>
                                    {{ category.name }}
                                </option>
                            {% endfor %}
                    </select>
                </div>
               
                <div>
                    <label for="animal-type"></label>
                    <form method="GET" action="" class="d-flex align-items-center gap-2">              
                        <input 
                            type="text" 
                            name="search" 
                            class="form-control shadow-sm w-auto" 
                            placeholder="Search..." 
                            value="{{ search_query }}" 
                            style="border-radius: 12px;">

                        <button 
                            type="submit" 
                            class="btn btn-secondary shadow-sm" 
                            >
                            <i class="fi fi-rr-search"></i>
                        </button>   
                    </form>
                </div>
            </div>
        </div>
 

    
    <div class="table-responsive">
        <table class="table table-bordered table-hover" id="news_article_table">
            <thead class="thead-dark">
                <tr>
                    <th><input type="checkbox" id="selectAll"></th>
                    <th>#</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Cover Photo</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Featured</th>
                    <th>Actions</th>    
                </tr>
            </thead>
            {% if newsarticles %}
            <tbody>
                {% for newsarticle in newsarticles %}
                    <tr>
                        <td><input type="checkbox" class="blogCheckbox" value="{{ newsarticle.id }}"></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ newsarticle.title }}</td>
                        <td>
                            {% if newsarticle.category %}
                            {{ newsarticle.category.name }}
                            {% else %}
                            Uncategorized
                            {% endif %}
                        </td>
                        <td>
                            {% if newsarticle.photo %}
                                <img src="{{ newsarticle.photo.url }}" 
                                    alt="{{ newsarticle.title }}" 
                                    style="width: 80px; height: 80px; object-fit: cover; border-radius: 10px; box-shadow: 0 2px 6px rgba(0,0,0,0.2);">
                            {% else %}
                                No Cover
                            {% endif %}
                        </td>
                        <td>{{ newsarticle.created_at }}</td>
                        <td>{{ newsarticle.updated_at }}</td>
                        {% if newsarticle.featured %}
                        <td>Yes</td>
                        {% else %}
                        <td>No</td>
                        {% endif %}
                       
                        <td class="text-center">
                            <!-- Action Buttons -->
                            <a href="{% url 'news&articles:news_artic_detail' slug=newsarticle.slug %}" 
                                class="btn btn-outline-success btn-sm"
                                target="_blank">View</a>

                            <a 
                                class="btn btn-outline-warning btn-sm"
                                href= " {% url 'management:edit_news&articles' id=newsarticle.id %}">
                                Edit
                            </a>

                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
    </table>
    <div class="alert alert-warning text-center">
        No results.
    </div>
    {% endif %}
    </div>
</div>

    <!-- Delete Modal -->
    <div class="modal fade" id="deleteNewsArticleModal" tabindex="-1" aria-labelledby="deleteNewsArticleLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="delete-form" method="POST" action="{% url 'management:delete_news&articles' %}">
                    {% csrf_token %}
                    <input type="hidden" name="selected_ids" id="ids"  value="">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteNewsArticleLabel">Delete Post</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>Are sure you want to delete: <span id="delete-count"></span> posts?</p>
                    </div>
                    <div class="modal-footer">
                        
                        <button type="button" class="btn btn-" data-bs-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-danger" id="confirm-delete">Yes</button>
                    </div>
                </form>
            </div>
        </div>
    </div> 

{% endblock content %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/36.0.1/full/ckeditor.js"></script>

{% comment %} ckeditor5 {% endcomment %}

<script src="{% static 'management/js/news-article.js' %}"></script>

{% endblock scripts %}